# Generated by Django 4.2.30 on 2026-04-15 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=100, verbose_name='ID сессии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата расчёта')),
                ('cards_snapshot', models.JSONField(verbose_name='Снимок данных карт')),
                ('total_overpayment', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая переплата')),
                ('payoff_months', models.IntegerField(default=0, verbose_name='Месяцев до погашения')),
                ('recommended_strategy', models.TextField(blank=True, verbose_name='Рекомендуемая стратегия')),
            ],
            options={
                'verbose_name': 'История расчёта',
                'verbose_name_plural': 'История расчётов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название карты')),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Кредитный лимит')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Годовая ставка (%)')),
                ('current_debt', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Текущая задолженность')),
                ('min_payment_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Мин. платёж (% от долга)')),
            ],
            options={
                'verbose_name': 'Кредитная карта',
                'verbose_name_plural': 'Кредитные карты',
            },
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(verbose_name='Номер месяца')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма платежа')),
                ('interest_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Проценты за месяц')),
                ('remaining_debt', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Остаток долга')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.creditcard', verbose_name='Карта')),
            ],
            options={
                'verbose_name': 'График платежа',
                'verbose_name_plural': 'Графики платежей',
                'ordering': ['card', 'month'],
            },
        ),
    ]
